### PR TITLE
Fix get env typespec

### LINKED ISSUE #17: Typespec is incorrect for get_env
It doesn't show as returning nil or a value, but rather a tagged tuple like fetch_env

### PR DESCRIPTION
**Pull request by zachdaniel**
Fixes #17

### CODE REVIEW

File: lib/confex.ex [hunk 1]
```diff
@@ -180,7 +180,7 @@ can not resolve key MY_TEST_ENV value via adapter Elixir.Confex.Adapters.SystemE
       ...> 1 = #{__MODULE__}.get_env(:myapp, :test_var)
       1
   """
-  @spec get_env(app :: Application.app(), key :: Application.key()) :: {:ok, Application.value()} | {:error, any()}
+  @spec get_env(app :: Application.app(), key :: Application.key(), term) :: Application.value()
```
Comment (AndrewDryga) [inline lib/confex.ex]: Can you, please, name the third argument as it is named in function?

Comment (zachdaniel) [inline lib/confex.ex]: Will do, thanks!

**Comment by AndrewDryga** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 possible new issue (including those that may have been commented here).

But beware that this branch is **[1 commit behind the `Nebo15:master` branch](https://github.com/Nebo15/confex/compare/albert-io:fix-get-env-typespec...Nebo15:master)**, and a review of an up to date branch would produce more accurate results.

You can see more details about this review at https://ebertapp.io/github/Nebo15/confex/pulls/18.

**Comment by zachdaniel** [comment]
Wasn't sure how you would prefer the line broken.  Happy to change it according to your preferences.

**Comment by AndrewDryga** [comment]
Great job, thanks! 👍
